/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as NewToBcRouteImport } from './routes/new-to-bc'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConsultationRouteImport } from './routes/consultation'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ResourcesIndexRouteImport } from './routes/resources.index'
import { Route as CommunityIndexRouteImport } from './routes/community.index'
import { Route as CitiesIndexRouteImport } from './routes/cities.index'
import { Route as ServicesProtectYourFamilyRouteImport } from './routes/services.protect-your-family'
import { Route as ServicesPlanYourFutureRouteImport } from './routes/services.plan-your-future'
import { Route as ServicesFinanceYourHomeRouteImport } from './routes/services.finance-your-home'
import { Route as ServicesBuyYourHomeRouteImport } from './routes/services.buy-your-home'
import { Route as ServicesBuildWealthRouteImport } from './routes/services.build-wealth'
import { Route as ResourcesVideosRouteImport } from './routes/resources.videos'
import { Route as ResourcesGuidesRouteImport } from './routes/resources.guides'
import { Route as ResourcesCostOfLivingCalculatorRouteImport } from './routes/resources.cost-of-living-calculator'
import { Route as ResourcesArticlesRouteImport } from './routes/resources.articles'
import { Route as CommunityStoriesRouteImport } from './routes/community.stories'
import { Route as CommunityEventsRouteImport } from './routes/community.events'
import { Route as CitiesCompareRouteImport } from './routes/cities.compare'
import { Route as CitiesCitySlugRouteImport } from './routes/cities.$citySlug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const NewToBcRoute = NewToBcRouteImport.update({
  id: '/new-to-bc',
  path: '/new-to-bc',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultationRoute = ConsultationRouteImport.update({
  id: '/consultation',
  path: '/consultation',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityIndexRoute = CommunityIndexRouteImport.update({
  id: '/community/',
  path: '/community/',
  getParentRoute: () => rootRouteImport,
} as any)
const CitiesIndexRoute = CitiesIndexRouteImport.update({
  id: '/cities/',
  path: '/cities/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesProtectYourFamilyRoute =
  ServicesProtectYourFamilyRouteImport.update({
    id: '/services/protect-your-family',
    path: '/services/protect-your-family',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesPlanYourFutureRoute = ServicesPlanYourFutureRouteImport.update({
  id: '/services/plan-your-future',
  path: '/services/plan-your-future',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesFinanceYourHomeRoute = ServicesFinanceYourHomeRouteImport.update({
  id: '/services/finance-your-home',
  path: '/services/finance-your-home',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesBuyYourHomeRoute = ServicesBuyYourHomeRouteImport.update({
  id: '/services/buy-your-home',
  path: '/services/buy-your-home',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesBuildWealthRoute = ServicesBuildWealthRouteImport.update({
  id: '/services/build-wealth',
  path: '/services/build-wealth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesVideosRoute = ResourcesVideosRouteImport.update({
  id: '/resources/videos',
  path: '/resources/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesGuidesRoute = ResourcesGuidesRouteImport.update({
  id: '/resources/guides',
  path: '/resources/guides',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesCostOfLivingCalculatorRoute =
  ResourcesCostOfLivingCalculatorRouteImport.update({
    id: '/resources/cost-of-living-calculator',
    path: '/resources/cost-of-living-calculator',
    getParentRoute: () => rootRouteImport,
  } as any)
const ResourcesArticlesRoute = ResourcesArticlesRouteImport.update({
  id: '/resources/articles',
  path: '/resources/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityStoriesRoute = CommunityStoriesRouteImport.update({
  id: '/community/stories',
  path: '/community/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityEventsRoute = CommunityEventsRouteImport.update({
  id: '/community/events',
  path: '/community/events',
  getParentRoute: () => rootRouteImport,
} as any)
const CitiesCompareRoute = CitiesCompareRouteImport.update({
  id: '/cities/compare',
  path: '/cities/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const CitiesCitySlugRoute = CitiesCitySlugRouteImport.update({
  id: '/cities/$citySlug',
  path: '/cities/$citySlug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/consultation': typeof ConsultationRoute
  '/contact': typeof ContactRoute
  '/journey': typeof JourneyRoute
  '/new-to-bc': typeof NewToBcRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/cities/$citySlug': typeof CitiesCitySlugRoute
  '/cities/compare': typeof CitiesCompareRoute
  '/community/events': typeof CommunityEventsRoute
  '/community/stories': typeof CommunityStoriesRoute
  '/resources/articles': typeof ResourcesArticlesRoute
  '/resources/cost-of-living-calculator': typeof ResourcesCostOfLivingCalculatorRoute
  '/resources/guides': typeof ResourcesGuidesRoute
  '/resources/videos': typeof ResourcesVideosRoute
  '/services/build-wealth': typeof ServicesBuildWealthRoute
  '/services/buy-your-home': typeof ServicesBuyYourHomeRoute
  '/services/finance-your-home': typeof ServicesFinanceYourHomeRoute
  '/services/plan-your-future': typeof ServicesPlanYourFutureRoute
  '/services/protect-your-family': typeof ServicesProtectYourFamilyRoute
  '/cities/': typeof CitiesIndexRoute
  '/community/': typeof CommunityIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/consultation': typeof ConsultationRoute
  '/contact': typeof ContactRoute
  '/journey': typeof JourneyRoute
  '/new-to-bc': typeof NewToBcRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/cities/$citySlug': typeof CitiesCitySlugRoute
  '/cities/compare': typeof CitiesCompareRoute
  '/community/events': typeof CommunityEventsRoute
  '/community/stories': typeof CommunityStoriesRoute
  '/resources/articles': typeof ResourcesArticlesRoute
  '/resources/cost-of-living-calculator': typeof ResourcesCostOfLivingCalculatorRoute
  '/resources/guides': typeof ResourcesGuidesRoute
  '/resources/videos': typeof ResourcesVideosRoute
  '/services/build-wealth': typeof ServicesBuildWealthRoute
  '/services/buy-your-home': typeof ServicesBuyYourHomeRoute
  '/services/finance-your-home': typeof ServicesFinanceYourHomeRoute
  '/services/plan-your-future': typeof ServicesPlanYourFutureRoute
  '/services/protect-your-family': typeof ServicesProtectYourFamilyRoute
  '/cities': typeof CitiesIndexRoute
  '/community': typeof CommunityIndexRoute
  '/resources': typeof ResourcesIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/consultation': typeof ConsultationRoute
  '/contact': typeof ContactRoute
  '/journey': typeof JourneyRoute
  '/new-to-bc': typeof NewToBcRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/cities/$citySlug': typeof CitiesCitySlugRoute
  '/cities/compare': typeof CitiesCompareRoute
  '/community/events': typeof CommunityEventsRoute
  '/community/stories': typeof CommunityStoriesRoute
  '/resources/articles': typeof ResourcesArticlesRoute
  '/resources/cost-of-living-calculator': typeof ResourcesCostOfLivingCalculatorRoute
  '/resources/guides': typeof ResourcesGuidesRoute
  '/resources/videos': typeof ResourcesVideosRoute
  '/services/build-wealth': typeof ServicesBuildWealthRoute
  '/services/buy-your-home': typeof ServicesBuyYourHomeRoute
  '/services/finance-your-home': typeof ServicesFinanceYourHomeRoute
  '/services/plan-your-future': typeof ServicesPlanYourFutureRoute
  '/services/protect-your-family': typeof ServicesProtectYourFamilyRoute
  '/cities/': typeof CitiesIndexRoute
  '/community/': typeof CommunityIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/consultation'
    | '/contact'
    | '/journey'
    | '/new-to-bc'
    | '/sitemap.xml'
    | '/cities/$citySlug'
    | '/cities/compare'
    | '/community/events'
    | '/community/stories'
    | '/resources/articles'
    | '/resources/cost-of-living-calculator'
    | '/resources/guides'
    | '/resources/videos'
    | '/services/build-wealth'
    | '/services/buy-your-home'
    | '/services/finance-your-home'
    | '/services/plan-your-future'
    | '/services/protect-your-family'
    | '/cities/'
    | '/community/'
    | '/resources/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/consultation'
    | '/contact'
    | '/journey'
    | '/new-to-bc'
    | '/sitemap.xml'
    | '/cities/$citySlug'
    | '/cities/compare'
    | '/community/events'
    | '/community/stories'
    | '/resources/articles'
    | '/resources/cost-of-living-calculator'
    | '/resources/guides'
    | '/resources/videos'
    | '/services/build-wealth'
    | '/services/buy-your-home'
    | '/services/finance-your-home'
    | '/services/plan-your-future'
    | '/services/protect-your-family'
    | '/cities'
    | '/community'
    | '/resources'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/consultation'
    | '/contact'
    | '/journey'
    | '/new-to-bc'
    | '/sitemap.xml'
    | '/cities/$citySlug'
    | '/cities/compare'
    | '/community/events'
    | '/community/stories'
    | '/resources/articles'
    | '/resources/cost-of-living-calculator'
    | '/resources/guides'
    | '/resources/videos'
    | '/services/build-wealth'
    | '/services/buy-your-home'
    | '/services/finance-your-home'
    | '/services/plan-your-future'
    | '/services/protect-your-family'
    | '/cities/'
    | '/community/'
    | '/resources/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ConsultationRoute: typeof ConsultationRoute
  ContactRoute: typeof ContactRoute
  JourneyRoute: typeof JourneyRoute
  NewToBcRoute: typeof NewToBcRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  CitiesCitySlugRoute: typeof CitiesCitySlugRoute
  CitiesCompareRoute: typeof CitiesCompareRoute
  CommunityEventsRoute: typeof CommunityEventsRoute
  CommunityStoriesRoute: typeof CommunityStoriesRoute
  ResourcesArticlesRoute: typeof ResourcesArticlesRoute
  ResourcesCostOfLivingCalculatorRoute: typeof ResourcesCostOfLivingCalculatorRoute
  ResourcesGuidesRoute: typeof ResourcesGuidesRoute
  ResourcesVideosRoute: typeof ResourcesVideosRoute
  ServicesBuildWealthRoute: typeof ServicesBuildWealthRoute
  ServicesBuyYourHomeRoute: typeof ServicesBuyYourHomeRoute
  ServicesFinanceYourHomeRoute: typeof ServicesFinanceYourHomeRoute
  ServicesPlanYourFutureRoute: typeof ServicesPlanYourFutureRoute
  ServicesProtectYourFamilyRoute: typeof ServicesProtectYourFamilyRoute
  CitiesIndexRoute: typeof CitiesIndexRoute
  CommunityIndexRoute: typeof CommunityIndexRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-to-bc': {
      id: '/new-to-bc'
      path: '/new-to-bc'
      fullPath: '/new-to-bc'
      preLoaderRoute: typeof NewToBcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultation': {
      id: '/consultation'
      path: '/consultation'
      fullPath: '/consultation'
      preLoaderRoute: typeof ConsultationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/': {
      id: '/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/': {
      id: '/community/'
      path: '/community'
      fullPath: '/community/'
      preLoaderRoute: typeof CommunityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cities/': {
      id: '/cities/'
      path: '/cities'
      fullPath: '/cities/'
      preLoaderRoute: typeof CitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/protect-your-family': {
      id: '/services/protect-your-family'
      path: '/services/protect-your-family'
      fullPath: '/services/protect-your-family'
      preLoaderRoute: typeof ServicesProtectYourFamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/plan-your-future': {
      id: '/services/plan-your-future'
      path: '/services/plan-your-future'
      fullPath: '/services/plan-your-future'
      preLoaderRoute: typeof ServicesPlanYourFutureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/finance-your-home': {
      id: '/services/finance-your-home'
      path: '/services/finance-your-home'
      fullPath: '/services/finance-your-home'
      preLoaderRoute: typeof ServicesFinanceYourHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/buy-your-home': {
      id: '/services/buy-your-home'
      path: '/services/buy-your-home'
      fullPath: '/services/buy-your-home'
      preLoaderRoute: typeof ServicesBuyYourHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/build-wealth': {
      id: '/services/build-wealth'
      path: '/services/build-wealth'
      fullPath: '/services/build-wealth'
      preLoaderRoute: typeof ServicesBuildWealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/videos': {
      id: '/resources/videos'
      path: '/resources/videos'
      fullPath: '/resources/videos'
      preLoaderRoute: typeof ResourcesVideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/guides': {
      id: '/resources/guides'
      path: '/resources/guides'
      fullPath: '/resources/guides'
      preLoaderRoute: typeof ResourcesGuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/cost-of-living-calculator': {
      id: '/resources/cost-of-living-calculator'
      path: '/resources/cost-of-living-calculator'
      fullPath: '/resources/cost-of-living-calculator'
      preLoaderRoute: typeof ResourcesCostOfLivingCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/articles': {
      id: '/resources/articles'
      path: '/resources/articles'
      fullPath: '/resources/articles'
      preLoaderRoute: typeof ResourcesArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/stories': {
      id: '/community/stories'
      path: '/community/stories'
      fullPath: '/community/stories'
      preLoaderRoute: typeof CommunityStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/events': {
      id: '/community/events'
      path: '/community/events'
      fullPath: '/community/events'
      preLoaderRoute: typeof CommunityEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cities/compare': {
      id: '/cities/compare'
      path: '/cities/compare'
      fullPath: '/cities/compare'
      preLoaderRoute: typeof CitiesCompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cities/$citySlug': {
      id: '/cities/$citySlug'
      path: '/cities/$citySlug'
      fullPath: '/cities/$citySlug'
      preLoaderRoute: typeof CitiesCitySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ConsultationRoute: ConsultationRoute,
  ContactRoute: ContactRoute,
  JourneyRoute: JourneyRoute,
  NewToBcRoute: NewToBcRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  CitiesCitySlugRoute: CitiesCitySlugRoute,
  CitiesCompareRoute: CitiesCompareRoute,
  CommunityEventsRoute: CommunityEventsRoute,
  CommunityStoriesRoute: CommunityStoriesRoute,
  ResourcesArticlesRoute: ResourcesArticlesRoute,
  ResourcesCostOfLivingCalculatorRoute: ResourcesCostOfLivingCalculatorRoute,
  ResourcesGuidesRoute: ResourcesGuidesRoute,
  ResourcesVideosRoute: ResourcesVideosRoute,
  ServicesBuildWealthRoute: ServicesBuildWealthRoute,
  ServicesBuyYourHomeRoute: ServicesBuyYourHomeRoute,
  ServicesFinanceYourHomeRoute: ServicesFinanceYourHomeRoute,
  ServicesPlanYourFutureRoute: ServicesPlanYourFutureRoute,
  ServicesProtectYourFamilyRoute: ServicesProtectYourFamilyRoute,
  CitiesIndexRoute: CitiesIndexRoute,
  CommunityIndexRoute: CommunityIndexRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
